FLASK_APP = "app.py"
FLASK_SECRET_KEY = "hereisthesecretkey"
FLASK_DATABASE_FILE = "recipe_database"
FLASK_SQLALCHEMY_ECHO = 1
FLASK_JWT_SECRET_KEY="super-secret"
FLASK_SQLALCHEMY_TRACK_MODIFICATIONS = 0